# -*- coding: utf-8 -*-
"""02_score_extraction

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GCdPz14C1_eFQ-VX4NHyRc1UTEcUMZED
"""

"""
02_score_extraction.py
Extract L2/L3 risk scores from trained models
Usage: python 02_score_extraction.py \
    --jsonl ko_counseling_92_www.jsonl \
    --model_dir ./models \
    --output ko_turn_scores.csv
"""

import argparse
import json
import pandas as pd
import numpy as np
import torch
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification)
import os

MODEL_NAME = 'klue/roberta-base'
MAX_LEN = 256
BATCH_SIZE = 32

def get_scores(texts, model, tokenizer,
               device, batch_size=BATCH_SIZE):
    model.eval()
    all_scores = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]
        enc = tokenizer(
            batch,
            max_length=MAX_LEN,
            padding=True,
            truncation=True,
            return_tensors='pt')
        enc = {k: v.to(device)
               for k, v in enc.items()}
        with torch.no_grad():
            out = model(**enc)
        probs = torch.softmax(
            out.logits, dim=1)
        scores = probs[:,1].cpu().numpy()
        all_scores.extend(scores.tolist())
        if i % 2000 == 0:
            print(f"  {i}/{len(texts)}...")
    return all_scores

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--jsonl',
        default='ko_counseling_92_www.jsonl')
    parser.add_argument(
        '--model_dir',
        default='./models')
    parser.add_argument(
        '--output',
        default='ko_turn_scores.csv')
    args = parser.parse_args()

    device = 'cuda' if torch.cuda.is_available() \
             else 'cpu'
    print(f"Device: {device}")

    # 모델 로드
    tokenizer = AutoTokenizer.from_pretrained(
        MODEL_NAME)

    # 체크포인트 자동 탐지
    def load_best_checkpoint(model_dir):
        checkpoints = [
            d for d in os.listdir(model_dir)
            if d.startswith('checkpoint-')]
        if not checkpoints:
            return model_dir
        # 가장 높은 번호 = 마지막
        best = sorted(
            checkpoints,
            key=lambda x: int(
                x.split('-')[1]))[-1]
        return os.path.join(model_dir, best)

    l2_path = load_best_checkpoint(
        os.path.join(args.model_dir, 'L2'))
    l3_path = load_best_checkpoint(
        os.path.join(args.model_dir, 'L3'))

    print(f"L2 model: {l2_path}")
    print(f"L3 model: {l3_path}")

    model_l2 = AutoModelForSequenceClassification\
        .from_pretrained(l2_path).to(device)
    model_l3 = AutoModelForSequenceClassification\
        .from_pretrained(l3_path).to(device)

    # JSONL 로드
    dialogues = []
    with open(args.jsonl, 'r',
              encoding='utf-8-sig') as f:
        for line in f:
            line = line.strip()
            if line:
                dialogues.append(
                    json.loads(line))
    print(f"Dialogues: {len(dialogues)}")

    # 내담자 발화 추출
    records = []
    for d in dialogues:
        for i, turn in enumerate(d['turns']):
            if turn.get('spk') == '내담자':
                records.append({
                    'dialogue_id':
                        d['dialogue_id'],
                    'turn_id': i,
                    'text': turn.get('text','')
                })

    turn_df = pd.DataFrame(records)
    print(f"Client turns: {len(turn_df)}")

    texts = turn_df['text'].tolist()

    print("\nComputing L2 scores...")
    turn_df['L2_score'] = get_scores(
        texts, model_l2, tokenizer, device)

    print("Computing L3 scores...")
    turn_df['L3_score'] = get_scores(
        texts, model_l3, tokenizer, device)

    turn_df.to_csv(
        args.output, index=False,
        encoding='utf-8-sig')
    print(f"\n✅ Saved: {args.output}")
    print(f"L2 mean: {turn_df['L2_score'].mean():.3f}")
    print(f"L3 mean: {turn_df['L3_score'].mean():.3f}")

if __name__ == '__main__':
    main()

"""
02_score_extraction.py
Extract L2/L3 risk scores from trained models
Usage: python 02_score_extraction.py \
    --jsonl ko_counseling_92_www.jsonl \
    --model_dir ./models \
    --output ko_turn_scores.csv
"""

import argparse
import json
import pandas as pd
import numpy as np
import torch
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification)
import os

MODEL_NAME = 'klue/roberta-base'
MAX_LEN = 256
BATCH_SIZE = 32

def get_scores(texts, model, tokenizer,
               device, batch_size=BATCH_SIZE):
    model.eval()
    all_scores = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]
        enc = tokenizer(
            batch,
            max_length=MAX_LEN,
            padding=True,
            truncation=True,
            return_tensors='pt')
        enc = {k: v.to(device)
               for k, v in enc.items()}
        with torch.no_grad():
            out = model(**enc)
        probs = torch.softmax(
            out.logits, dim=1)
        scores = probs[:,1].cpu().numpy()
        all_scores.extend(scores.tolist())
        if i % 2000 == 0:
            print(f"  {i}/{len(texts)}...")
    return all_scores

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--jsonl',
        default='ko_counseling_92_www.jsonl')
    parser.add_argument(
        '--model_dir',
        default='./models')
    parser.add_argument(
        '--output',
        default='ko_turn_scores.csv')
    args = parser.parse_args()

    device = 'cuda' if torch.cuda.is_available() \
             else 'cpu'
    print(f"Device: {device}")

    # 모델 로드
    tokenizer = AutoTokenizer.from_pretrained(
        MODEL_NAME)

    # 체크포인트 자동 탐지
    def load_best_checkpoint(model_dir):
        checkpoints = [
            d for d in os.listdir(model_dir)
            if d.startswith('checkpoint-')]
        if not checkpoints:
            return model_dir
        # 가장 높은 번호 = 마지막
        best = sorted(
            checkpoints,
            key=lambda x: int(
                x.split('-')[1]))[-1]
        return os.path.join(model_dir, best)

    l2_path = load_best_checkpoint(
        os.path.join(args.model_dir, 'L2'))
    l3_path = load_best_checkpoint(
        os.path.join(args.model_dir, 'L3'))

    print(f"L2 model: {l2_path}")
    print(f"L3 model: {l3_path}")

    model_l2 = AutoModelForSequenceClassification\
        .from_pretrained(l2_path).to(device)
    model_l3 = AutoModelForSequenceClassification\
        .from_pretrained(l3_path).to(device)

    # JSONL 로드
    dialogues = []
    with open(args.jsonl, 'r',
              encoding='utf-8-sig') as f:
        for line in f:
            line = line.strip()
            if line:
                dialogues.append(
                    json.loads(line))
    print(f"Dialogues: {len(dialogues)}")

    # 내담자 발화 추출
    records = []
    for d in dialogues:
        for i, turn in enumerate(d['turns']):
            if turn.get('spk') == '내담자':
                records.append({
                    'dialogue_id':
                        d['dialogue_id'],
                    'turn_id': i,
                    'text': turn.get('text','')
                })

    turn_df = pd.DataFrame(records)
    print(f"Client turns: {len(turn_df)}")

    texts = turn_df['text'].tolist()

    print("\nComputing L2 scores...")
    turn_df['L2_score'] = get_scores(
        texts, model_l2, tokenizer, device)

    print("Computing L3 scores...")
    turn_df['L3_score'] = get_scores(
        texts, model_l3, tokenizer, device)

    turn_df.to_csv(
        args.output, index=False,
        encoding='utf-8-sig')
    print(f"\n✅ Saved: {args.output}")
    print(f"L2 mean: {turn_df['L2_score'].mean():.3f}")
    print(f"L3 mean: {turn_df['L3_score'].mean():.3f}")

if __name__ == '__main__':
    main()
